ALTER TABLE outbox_events
    ADD COLUMN IF NOT EXISTS kafka_key VARCHAR(255),
    ADD COLUMN IF NOT EXISTS payload_type VARCHAR(255),
    ADD COLUMN IF NOT EXISTS lease_owner VARCHAR(255),
    ADD COLUMN IF NOT EXISTS lease_expiration TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS published_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS last_error TEXT;

CREATE INDEX IF NOT EXISTS idx_outbox_ready
    ON outbox_events (status, next_attempt_at, created_at, id)
    WHERE status IN ('PENDING', 'IN_FLIGHT');
