name: CI/CD Pipeline

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

permissions:
  contents: read
  packages: write

env:
  READ_PACKAGES_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}
  GPR_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN || secrets.GITHUB_TOKEN }}

jobs:
  java-ci:
    uses: pploc/gym-infra/.github/workflows/reusable-java-ci.yml@develop
    with:
      service_path: '.'
    secrets: inherit

  docker-build:
    needs: java-ci
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    uses: pploc/gym-infra/.github/workflows/reusable-docker-build.yml@develop
    with:
      service_name: 'ms-gym-member'
      context: '.'
    secrets: inherit
